POST https://labedrink.herokuapp.com/drink
Content-Type: application/json
Authorization: fernando-aparecido-aragon

{
    "name":"fernidistica",
    "description":"bebida aromatizante",
    "rating":10
}

###

GET https://labedrink.herokuapp.com/drink/:id
Authorization: fernando-aparecido-aragon


{






































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































name:"daniellisticas",
"description":" bebida adocicada",
":rating":9.5 "
}
###

PUT https://labedrink.herokuapp.com/drink/:id
Content-Type: application/json
Authorization: fernando-aparecido-aragon
{
":name:"pipoiii!!!",
"description:"bebida de gosto amargo"
rating": 8.4
}

###
DELETE https://labedrink.herokuapp.com/drink/:id

Authorization: fernando-aparecido-aragon
""
{
    ":name:"pipoiii!!!"
"rating": 8.4
}
